//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServisInfo_API.Models
{
    using System;
    
    public partial class DetaljiServisa_Report
    {
        public int ServisID { get; set; }
        public int KompanijaID { get; set; }
        public int KlijentID { get; set; }
        public int PonudaID { get; set; }
        public int UpitID { get; set; }
        public Nullable<System.DateTime> Datum_Upita { get; set; }
        public System.DateTime DatumK_reiranja_Ponude { get; set; }
        public Nullable<System.DateTime> Datum_Pocetka_Servisa { get; set; }
        public Nullable<System.DateTime> Datum_Zavrsetka_Servisa { get; set; }
        public Nullable<decimal> Konacna_Cijena { get; set; }
        public string Opis_Kvara { get; set; }
        public string Odgovor { get; set; }
        public string Marka_uredjaja { get; set; }
        public string Model_uredjaja { get; set; }
        public string Ime_i_prezime_klijenta { get; set; }
        public string Naziv_kompanije { get; set; }
    }
}
