//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServisInfo_API.Models
{
    using System;
    
    public partial class KompanijeUpitResult
    {
        public int UpitID { get; set; }
        public int KompanijaID { get; set; }
        public string Naziv { get; set; }
    }
}
