//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServisInfo_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModeliUredjaja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ModeliUredjaja()
        {
            this.Upiti = new HashSet<Upiti>();
        }
    
        public string Naziv { get; set; }
        public int MarkaUredjajaID { get; set; }
        public int ModelUredjajaID { get; set; }
    
        public virtual MarkeUredjaja MarkeUredjaja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Upiti> Upiti { get; set; }
    }
}
