//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServisInfo_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ocjene
    {
        public int OcjenaID { get; set; }
        public decimal Ocjena { get; set; }
        public System.DateTime Datum { get; set; }
        public int VrstaOcjeneID { get; set; }
        public int ServisID { get; set; }
        public int KlijentID { get; set; }
    
        public virtual Klijenti Klijenti { get; set; }
        public virtual Servisi Servisi { get; set; }
        public virtual VrsteOcjena VrsteOcjena { get; set; }
    }
}
