//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServisInfo_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servisi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Servisi()
        {
            this.Ocjene = new HashSet<Ocjene>();
        }
    
        public int ServisID { get; set; }
        public System.DateTime DatumPrihvatanja { get; set; }
        public Nullable<System.DateTime> DatumPocetka { get; set; }
        public Nullable<System.DateTime> DatumZavršetka { get; set; }
        public Nullable<decimal> Cijena { get; set; }
        public Nullable<int> TrajanjeDani { get; set; }
        public int KompanijaID { get; set; }
        public int PonudaID { get; set; }
    
        public virtual Kompanije Kompanije { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ocjene> Ocjene { get; set; }
        public virtual Ponude Ponude { get; set; }
    }
}
